name = "daemons"
main = "src/index.ts"
compatibility_date = "2024-11-01"

assets = { directory = "../frontend/dist", binding = "ASSETS" }

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "daemons-db"
database_id = "c8f89af0-ba44-45c7-b9de-c2b91e920034"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "b78b72f94acd47678674733684eef98e"

[[kv_namespaces]]
binding = "CIRCUIT_BREAKER"
id = "4465c69e737948dfb045b3dc694941b5"

[triggers]
crons = ["*/2 * * * *"]
